"""empty message

Revision ID: 094a164ddd89
Revises: 0966f4b2a718
Create Date: 2022-06-04 21:49:01.607928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094a164ddd89'
down_revision = '0966f4b2a718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('posts', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('posts', sa.Column('content', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content')
    op.drop_column('posts', 'title')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
