"""empty message

Revision ID: 93bc664b776c
Revises: 3f83df5aaf13
Create Date: 2022-06-04 14:36:58.487896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bc664b776c'
down_revision = '3f83df5aaf13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.add_column('users', sa.Column('uid', sa.Integer(), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.drop_column('users', 'uid')
    op.drop_table('posts')
    # ### end Alembic commands ###
