"""empty message

Revision ID: e53d32e96172
Revises: 094a164ddd89
Create Date: 2022-06-04 21:57:32.870477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53d32e96172'
down_revision = '094a164ddd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('desc', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('pic', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'pic')
    op.drop_column('user_profiles', 'desc')
    # ### end Alembic commands ###
